version: 2.1
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: |
          make docker-image
          make docker-test

      - run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          make docker-push
