# Generated by Django 2.1.3 on 2018-11-13 02:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailimages', '0021_image_file_hash'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogIndex',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('date', models.DateField()),
                ('body', wagtail.core.fields.RichTextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ConcertDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateTimeField()),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RenameModel(
            old_name='SimplePage',
            new_name='BasicPage',
        ),
        migrations.RemoveField(
            model_name='performancedate',
            name='concert',
        ),
        migrations.CreateModel(
            name='ActiveRosterMusician',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('main.person',),
        ),
        migrations.AlterModelOptions(
            name='basicpage',
            options={'verbose_name': 'Basic Page'},
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AlterModelOptions(
            name='instrumentmodel',
            options={'verbose_name': 'Instrument'},
        ),
        migrations.AlterModelOptions(
            name='performer',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='concert',
            name='season',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='performer',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.DeleteModel(
            name='PerformanceDate',
        ),
        migrations.AddField(
            model_name='concertdate',
            name='concert',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_date', to='main.Concert'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.Person'),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='blog_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='concert',
            name='roster',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='main.ActiveRosterMusician'),
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_date',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='main.ConcertDate'),
        ),
    ]
