# Generated by Django 2.1.3 on 2018-12-13 02:23

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20181113_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='season',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='instrument',
            field=modelcluster.fields.ParentalManyToManyField(related_name='person_instrument', to='main.InstrumentModel'),
        ),
    ]
