# Generated by Django 2.1.2 on 2018-11-03 01:34

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('main', '0002_blogindex_blogpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertRoster',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('performer', modelcluster.fields.ParentalManyToManyField(related_name='_concertroster_performer_+', to='main.Person')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'Homepage'},
        ),
        migrations.AlterModelOptions(
            name='performancedate',
            options={'ordering': ['date']},
        ),
        migrations.AlterModelOptions(
            name='simplepage',
            options={'verbose_name': 'Basic Page'},
        ),
    ]
