# Generated by Django 2.1.5 on 2019-01-05 04:07

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190105_0337'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='promo_copy',
            field=wagtail.core.fields.RichTextField(default='Foo Bar'),
            preserve_default=False,
        ),
    ]
