# Generated by Django 2.1.2 on 2018-11-03 03:59

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20181103_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertroster',
            name='performer',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='main.Person'),
        ),
    ]
