# Generated by Django 2.2.3 on 2019-07-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_donate'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='legacy_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='concert',
            name='legacy_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='person',
            name='legacy_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
