# Generated by Django 2.1.2 on 2018-11-03 19:53

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20181103_0428'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertroster',
            options={'verbose_name': 'Concert Roster'},
        ),
        migrations.AddField(
            model_name='concert',
            name='performer',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='main.ActiveRosterMusician'),
        ),
    ]
