# Generated by Django 2.2.3 on 2019-07-19 22:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190716_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='promo_copy',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
