# Generated by Django 2.1.2 on 2018-11-03 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0040_page_draft_title'),
        ('main', '0007_auto_20181103_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='concertroster',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='concertroster',
            name='performer',
        ),
        migrations.RenameField(
            model_name='concert',
            old_name='performer',
            new_name='roster',
        ),
        migrations.DeleteModel(
            name='ConcertRoster',
        ),
    ]
