# Generated by Django 2.1.2 on 2018-11-05 13:33

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20181103_1959'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='performance_dates',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='main.PerformanceDate'),
        ),
    ]
