# Generated by Django 2.2.3 on 2019-07-19 22:30

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20190719_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='promo_copy',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
