# Generated by Django 2.1.2 on 2018-11-07 02:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_performance_performance_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('concert', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='concert_date', to='main.Concert')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.RemoveField(
            model_name='performancedate',
            name='concert',
        ),
        migrations.RemoveField(
            model_name='performance',
            name='performance_dates',
        ),
        migrations.DeleteModel(
            name='PerformanceDate',
        ),
        migrations.AddField(
            model_name='performance',
            name='performance_date',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='main.ConcertDate'),
        ),
    ]
