# Generated by Django 2.1.2 on 2018-11-07 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20181107_0204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrumentmodel',
            options={'verbose_name': 'Instrument'},
        ),
    ]
