# Generated by Django 2.2.3 on 2019-07-21 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_instrumentmodel_show_on_roster'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
