# Generated by Django 2.1.2 on 2018-11-08 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20181108_0131'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='season',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
