# Generated by Django 2.1.2 on 2018-11-08 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_concert_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcertSeason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=9, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='concert',
            name='season',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.ConcertSeason'),
        ),
    ]
