# Generated by Django 2.1.2 on 2018-11-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20181108_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='season',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.DeleteModel(
            name='ConcertSeason',
        ),
    ]
