# Generated by Django 2.1.2 on 2018-11-11 20:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0015_auto_20181108_1313'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SimplePage',
            new_name='BasicPage',
        ),
    ]
