# Generated by Django 2.2.3 on 2019-07-28 01:42

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20190723_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='performance',
            name='supplemental_text',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
