# Generated by Django 2.2.3 on 2019-07-28 21:22

from django.db import migrations
from django.db import models, migrations
from wagtail.core.rich_text import RichText


def convert_to_streamfield(apps, schema_editor):
    BasicPage = apps.get_model('main', 'BasicPage')
    for page in BasicPage.objects.all():
        if page.body.raw_text and not page.body:
            page.body = [('paragraph', RichText(page.body.raw_text))]
            page.save()


def convert_to_richtext(apps, schema_editor):
    BasicPage = apps.get_model('main', 'BasicPage')
    for page in BasicPage.objects.all():
        if page.body.raw_text is None:
            raw_text = ''.join([
                child.value.source for child in page.body
                if child.block_type == 'paragraph'
            ])
            page.body = raw_text
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20190728_1722'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext
        )
    ]
