# Generated by Django 2.2.3 on 2019-07-28 21:33

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20190728_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())]),
        ),
    ]
