# Generated by Django 2.2.3 on 2019-07-28 21:34

from django.db import migrations
from django.db import models, migrations
from wagtail.core.rich_text import RichText


def convert_to_streamfield(apps, schema_editor):
    Concert = apps.get_model('main', 'Concert')
    for page in Concert.objects.all():
        if page.description.raw_text and not page.description:
            page.description = [('paragraph', RichText(page.description.raw_text))]
            page.save()


def convert_to_richtext(apps, schema_editor):
    Concert = apps.get_model('main', 'Concert')
    for page in Concert.objects.all():
        if page.description.raw_text is None:
            raw_text = ''.join([
                child.value.source for child in page.description
                if child.block_type == 'paragraph'
            ])
            page.description = raw_text
            page.save()



class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20190728_1733'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext
        )
    ]
