# Generated by Django 2.2.3 on 2019-07-28 21:41

from django.db import migrations
from django.db import models, migrations
from wagtail.core.rich_text import RichText


def convert_to_streamfield(apps, schema_editor):
    Person = apps.get_model('main', 'Person')
    for page in Person.objects.all():
        if page.biography.raw_text and not page.biography:
            page.biography = [('paragraph', RichText(page.biography.raw_text))]
            page.save()


def convert_to_richtext(apps, schema_editor):
    Person = apps.get_model('main', 'Person')
    for page in Person.objects.all():
        if page.biography.raw_text is None:
            raw_text = ''.join([
                child.value.source for child in page.biography
                if child.block_type == 'paragraph'
            ])
            page.biography = raw_text
            page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20190728_1741'),
    ]

    operations = [
        migrations.RunPython(
            convert_to_streamfield,
            convert_to_richtext
        )
    ]
