# Generated by Django 2.2.3 on 2019-07-29 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_auto_20190728_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='composition',
            name='composer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='main.Person'),
        ),
    ]
