# Generated by Django 2.2.3 on 2019-07-31 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20190729_0838'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='concertperformer',
            name='unique concert performer',
        ),
        migrations.RemoveField(
            model_name='concertperformer',
            name='performer',
        ),
        migrations.AddField(
            model_name='concertperformer',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='main.Person'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='concertperformer',
            constraint=models.UniqueConstraint(fields=('concert', 'person'), name='unique concert performer'),
        ),
    ]
