# Generated by Django 2.2.3 on 2019-07-31 03:04

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20190730_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concertperformer',
            name='concert',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='performer', to='main.Concert'),
        ),
        migrations.AlterField(
            model_name='concertperformer',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.Person'),
        ),
    ]
