# Generated by Django 2.2.3 on 2019-08-01 05:52

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20190730_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='instrument',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, null=True, related_name='person_instrument', to='main.InstrumentModel'),
        ),
    ]
