# Generated by Django 2.2.4 on 2019-08-05 17:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20190801_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=wagtail.core.fields.RichTextField(default="ST. PAUL'S CHURCH, 315 WEST 22ND STREET"),
        ),
    ]
