# Generated by Django 2.2.4 on 2019-08-10 22:01

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20190805_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='description',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('button', wagtail.core.blocks.StructBlock([('button_text', wagtail.core.blocks.CharBlock(required=True)), ('button_link', wagtail.core.blocks.URLBlock(required=True))], template='main/blocks/button_block.html'))]),
        ),
    ]
