# Generated by Django 2.2.4 on 2019-08-28 12:37

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_basicpage_search_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='venue',
            field=wagtail.core.fields.RichTextField(default="St. Paul's Church, 315 West 22nd Street"),
        ),
    ]
