# Generated by Django 2.2.4 on 2019-09-01 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_newmemberrequest_newmemberrequestpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrumentmodel',
            name='weight',
            field=models.PositiveSmallIntegerField(null=True, unique=True),
        ),
    ]
