# Generated by Django 2.2.4 on 2019-09-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_instrumentmodel_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrumentmodel',
            name='weight',
            field=models.PositiveSmallIntegerField(blank=True, null=True, unique=True),
        ),
    ]
