# Generated by Django 2.2.4 on 2019-11-29 19:43

# This migration was needed to fix a problem caused by incorrectly overriding
# the 'set_url_path' method on concert objects. Concert objects need to have
# the concert season in the penultimate portion of the path. The correct way
# of doing this is to override 'get_url_parts'.
# Once this was corrected, paths then had the concert season listed twice
# in the url. This migration resets the url_path attribute so that
# 'get_url_parts' returns a correct formed path.

from django.db import migrations


def reset_url_paths(apps, schema_editor):
    c_idx = apps.get_model('main', 'ConcertIndex').objects.first()
    Concert = apps.get_model('main', 'Concert')
    for concert in Concert.objects.all():
        concert.url_path = c_idx.url_path + concert.slug + '/'
        concert.save()


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0051_concert_program_notes'),
    ]

    operations = [
        migrations.RunPython(reset_url_paths)
    ]
