# Generated by Django 2.2.10 on 2020-02-09 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20191129_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concertperformer',
            options={'ordering': ['sort_order']},
        ),
    ]
