# Generated by Django 3.1.1 on 2020-09-20 00:43

from django.db import migrations
import wagtail.contrib.table_block.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0057_formfield_clean_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicpage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('table', wagtail.contrib.table_block.blocks.TableBlock()), ('caption_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock()), ('image_max_width', wagtail.core.blocks.IntegerBlock()), ('caption', wagtail.core.blocks.CharBlock(required=False))], icon='image', template='main/blocks/caption-image.html')), ('block_quote', wagtail.core.blocks.StructBlock([('quote', wagtail.core.blocks.RichTextBlock(features=['italic'], required=True)), ('footer', wagtail.core.blocks.CharBlock()), ('alignment', wagtail.core.blocks.ChoiceBlock(choices=[('bc-left', 'Left'), ('bc-right', 'Right')]))], icon='openquote', template='main/blocks/block_quote.html')), ('highlight_link', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=True)), ('sub_heading', wagtail.core.blocks.CharBlock(required=True)), ('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('page', wagtail.core.blocks.PageChooserBlock(required=True))], icon='link', template='main/blocks/highlight_link.html')), ('personnel', wagtail.core.blocks.StructBlock([('left_caption', wagtail.core.blocks.CharBlock(required=False)), ('left_block', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('role', wagtail.core.blocks.CharBlock(required=False)), ('people', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))], required=False)))], required=False))), ('right_caption', wagtail.core.blocks.CharBlock(required=False)), ('right_block', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('role', wagtail.core.blocks.CharBlock(required=False)), ('people', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.URLBlock(required=False))])))])))], icon='user', template='main/blocks/personnel.html')), ('personnel_center', wagtail.core.blocks.StructBlock([('caption', wagtail.core.blocks.CharBlock()), ('names', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock(label='name')))], icon='user', template='main/blocks/personnel_center.html'))]),
        ),
    ]
