# Generated by Django 3.1.13 on 2021-07-04 15:42

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0060_auto_20200920_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('youtube_embed', wagtail.core.blocks.StructBlock([('youtube_id', wagtail.core.blocks.CharBlock())]))]),
        ),
    ]
