# Generated by Django 3.1.13 on 2021-08-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0061_auto_20210704_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='ticketing_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
